name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH 🔧
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Connect and deploy 🔧
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            sudo ./translate-backend-deploy.sh GITHUB_REPOSITORY=${{ github.repository }} LOKI_HOST=${{ secrets.LOKI_HOST }} LOKI_USER=${{ secrets.LOKI_USER }} LOKI_PASSWORD=${{ secrets.LOKI_PASSWORD }} SERVICE_PORT=${{ secrets.SERVICE_PORT }} ALLOW_UNSAFE_EVAL=${{ secrets.ALLOW_UNSAFE_EVAL }} &&
            exit
          "
